# Generated by Django 5.0.1 on 2024-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
