# Generated by Django 5.0.1 on 2024-01-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_participant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='categories',
            field=models.CharField(choices=[('full_marathon', 'Full Marathon'), ('half_marathon', 'Half Marathon'), ('10K_marathon', '10K MARATHON')], default='full_marathon', max_length=20),
        ),
    ]
